create table if not exists trip (
    id bigint primary key comment '记录主键',
    trip_number varchar(20) not null comment '对外展示的行程编号',
    user_id bigint not null comment '发布者用户ID',
    trip_type varchar(24) not null default 'DRIVER_TRIP' comment '行程类型：DRIVER_TRIP车主行程、PASSENGER_DEMAND乘客需求',
    publisher_role varchar(16) not null default 'DRIVER' comment '发布者身份：DRIVER、PASSENGER',
    captain_user_id bigint null comment '当前队长用户ID；乘客需求未匹配时为空',
    vehicle_id bigint null comment '发布者车辆ID；乘客需求为空',
    title varchar(128) not null default '' comment '展示标题',
    description varchar(1000) not null default '' comment '详细说明',
    expected_people int null comment '预计人数',
    start_name varchar(128) not null comment '起点名称',
    start_lat decimal(10,6) null comment '起点纬度',
    start_lng decimal(10,6) null comment '起点经度',
    start_location_name varchar(128) not null default '' comment '起点位置名称',
    start_location_address varchar(255) not null default '' comment '起点位置地址',
    start_latitude decimal(10,6) null comment '起点纬度',
    start_longitude decimal(10,6) null comment '起点经度',
    end_name varchar(128) not null comment '终点名称',
    end_lat decimal(10,6) null comment '终点纬度',
    end_lng decimal(10,6) null comment '终点经度',
    end_location_name varchar(128) not null default '' comment '终点位置名称',
    end_location_address varchar(255) not null default '' comment '终点位置地址',
    end_latitude decimal(10,6) null comment '终点纬度',
    end_longitude decimal(10,6) null comment '终点经度',
    route_summary varchar(255) null comment '路线汇总',
    route_polyline_key varchar(512) null comment '路线折线数据的对象存储Key',
    route_distance int null comment '路线距离',
    route_duration int null comment '路线时长',
    route_polyline mediumtext null comment '路线折线编码数据',
    waypoints_json text null comment '途经点列表JSON数据',
    departure_time datetime not null comment '出发时间',
    estimated_days int null comment '估算，单位为天',
    total_distance_meters int null comment '总计距离，单位为米',
    max_vehicle_count int not null comment '最高车辆数量',
    joined_vehicle_count int not null default 1 comment '加入车辆数量',
    vehicle_requirements varchar(128) not null default '不限' comment '车辆要求',
    budget_description varchar(128) null comment '预算说明',
    travel_depth varchar(16) not null comment '出行深度',
    public_flag tinyint(1) not null default 1 comment '是否公开：0否、1是',
    status varchar(20) not null comment '业务状态',
    auto_start_enabled tinyint(1) not null default 1 comment '是否到点自动出发',
    arrival_status varchar(24) not null default 'NOT_ARRIVED' comment '到达状态',
    arrival_entered_at datetime null comment '首次进入终点范围时间',
    arrival_decision_deadline datetime null comment '到达后最迟处理时间',
    continue_count int not null default 0 comment '继续行程次数',
    remark varchar(255) null comment '业务备注',
    actual_start_time datetime null comment '实际起点时间',
    actual_end_time datetime null comment '实际终点时间',
    created_at datetime not null comment '记录创建时间',
    updated_at datetime not null comment '记录最后更新时间',
    deleted tinyint(1) not null default 0 comment '逻辑删除标记：0未删除、1已删除',
    unique key uk_trip_number (trip_number),
    key idx_trip_user_status_time (user_id, status, departure_time),
    key idx_trip_captain_status (captain_user_id, status, departure_time),
    key idx_trip_public_status_time (public_flag, status, departure_time),
    key idx_trip_auto_start (auto_start_enabled, status, departure_time),
    key idx_trip_arrival_deadline (arrival_status, arrival_decision_deadline),
    key idx_trip_vehicle (vehicle_id)
) comment='行程表';


create table if not exists trip_route (
    id bigint primary key comment '记录主键',
    trip_id bigint null comment '行程ID',
    draft_id bigint null comment '草稿ID',
    route_plan_id bigint null comment '路线规划ID',
    origin json not null comment '路线起点信息',
    destination json not null comment '路线终点信息',
    waypoints json null comment '途经点',
    polyline mediumtext null comment '路线折线编码数据',
    plan_distance int null comment '规划距离',
    plan_duration int null comment '规划时长',
    provider_type varchar(32) not null comment '外部服务提供方类型',
    route_status varchar(16) not null default 'VALID' comment '路线状态',
    created_at datetime not null comment '记录创建时间',
    updated_at datetime not null comment '记录最后更新时间',
    deleted tinyint(1) not null default 0 comment '逻辑删除标记：0未删除、1已删除',
    unique key uk_trip_route_trip (trip_id, deleted),
    unique key uk_trip_route_draft (draft_id, deleted)
) comment='行程路线表';
alter table trip_route modify column provider_type varchar(32) not null COMMENT '外部服务提供方类型';

create table if not exists trip_waypoint (
    id bigint primary key comment '记录主键',
    trip_id bigint null comment '行程ID',
    draft_id bigint null comment '草稿ID',
    seq_no int not null comment '序号编号',
    place_name varchar(128) not null comment '地点名称',
    place_address varchar(255) not null default '' comment '地点详细地址',
    waypoint_type varchar(16) not null default 'REST' comment '途经点类型',
    lat decimal(10,6) null comment '纬度坐标',
    lng decimal(10,6) null comment '经度坐标',
    stay_minutes int null comment '预计停留时长，单位为分钟',
    remark varchar(255) not null default '' comment '业务备注',
    created_at datetime not null comment '记录创建时间',
    updated_at datetime not null comment '记录最后更新时间',
    deleted tinyint(1) not null default 0 comment '逻辑删除标记：0未删除、1已删除',
    key idx_waypoint_trip_seq (trip_id, seq_no),
    key idx_waypoint_draft_seq (draft_id, seq_no)
) comment='行程途经点表';

create table if not exists trip_member_snapshot (
    id bigint primary key comment '记录主键',
    trip_id bigint not null comment '行程ID',
    user_id bigint not null comment '平台用户ID',
    vehicle_id bigint null comment '车辆ID',
    member_role varchar(16) not null comment '成员角色',
    join_status varchar(20) not null comment '加入状态',
    nickname_snapshot varchar(64) null comment '昵称快照',
    vehicle_snapshot varchar(128) null comment '车辆快照',
    joined_at datetime null comment '加入时间',
    created_at datetime not null comment '记录创建时间',
    updated_at datetime not null comment '记录最后更新时间',
    key idx_member_trip_status (trip_id, join_status)
) comment='行程成员快照表';

create table if not exists trip_audit_log (
    id bigint primary key comment '记录主键',
    trip_id bigint not null comment '行程ID',
    user_id bigint not null comment '平台用户ID',
    operation_type varchar(32) not null comment '操作类型',
    before_json json null comment '操作前数据快照JSON',
    after_json json null comment '操作后数据快照JSON',
    remark varchar(255) null comment '业务备注',
    created_at datetime not null comment '记录创建时间',
    key idx_audit_trip_time (trip_id, created_at)
) comment='行程审核日志表';

create table if not exists trip_draft (
    id bigint primary key comment '记录主键',
    user_id bigint not null comment '平台用户ID',
    title varchar(128) not null default '' comment '展示标题',
    description varchar(1000) not null default '' comment '详细说明',
    start_location_json json null comment '起点位置JSON数据',
    end_location_json json null comment '终点位置JSON数据',
    waypoint_json json not null comment '途经点JSON数据',
    departure_time datetime null comment '出发时间',
    duration_days int null comment '时长，单位为天',
    people_count int null comment '人数数量',
    vehicle_requirements varchar(128) not null default '不限' comment '车辆要求',
    budget_description varchar(128) null comment '预算说明',
    notes varchar(500) null comment '补充说明',
    remark varchar(255) not null default '' comment '业务备注',
    draft_status varchar(16) not null default 'DRAFT' comment '草稿状态',
    published_trip_id bigint null comment '已发布行程ID',
    publish_idempotency_key varchar(64) null comment '发布幂等标识或存储Key',
    created_at datetime not null default current_timestamp comment '记录创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '记录最后更新时间',
    deleted tinyint not null default 0 comment '逻辑删除标记：0未删除、1已删除',
    key idx_trip_draft_user_status (user_id, draft_status, updated_at),
    unique key uk_trip_draft_publish_key (publish_idempotency_key, deleted)
) comment='行程草稿表';



create table if not exists trip_departure_exception (
    id bigint primary key comment '记录主键',
    trip_id bigint not null comment '行程ID',
    member_user_id bigint not null comment '异常成员用户ID',
    distance_m int null comment '成员与队长距离，米',
    exception_type varchar(32) not null comment '异常类型',
    exception_status varchar(20) not null default 'PENDING' comment '处理状态',
    handled_action varchar(20) null comment 'WAIT或CONTINUE',
    detected_at datetime not null comment '检测时间',
    handled_at datetime null comment '处理时间',
    created_at datetime not null comment '创建时间',
    updated_at datetime not null comment '更新时间',
    deleted tinyint(1) not null default 0 comment '逻辑删除',
    unique key uk_trip_departure_exception (trip_id, member_user_id, deleted),
    key idx_trip_departure_pending (trip_id, exception_status, detected_at)
) comment='自动出发成员范围异常表';

create table if not exists trip_arrival_state (
    id bigint primary key comment '记录主键',
    trip_id bigint not null comment '行程ID',
    captain_user_id bigint not null comment '队长用户ID',
    state varchar(24) not null default 'NOT_ARRIVED' comment '到达状态',
    first_entered_at datetime null comment '首次进入终点范围时间',
    prompted_at datetime null comment '提示时间',
    decision_deadline datetime null comment '超时自动结束时间',
    last_distance_m int null comment '最近一次到终点距离',
    decision_action varchar(20) null comment 'END、CONTINUE、AUTO_END',
    decided_at datetime null comment '决策时间',
    created_at datetime not null comment '创建时间',
    updated_at datetime not null comment '更新时间',
    deleted tinyint(1) not null default 0 comment '逻辑删除',
    unique key uk_trip_arrival_state (trip_id, deleted),
    key idx_trip_arrival_deadline (state, decision_deadline)
) comment='行程到达停留与开放式结束状态表';
