import { request } from "../utils/request"
export type ImageBizType = "USER_AVATAR" | "USER_DRIVER_LICENSE_FRONT" | "USER_DRIVER_LICENSE_BACK" | "VEHICLE_LICENSE_FRONT" | "VEHICLE_LICENSE_BACK" | "VEHICLE_PHOTO_FRONT" | "VEHICLE_PHOTO_REAR" | "VEHICLE_PHOTO_SIDE" | "VEHICLE_PHOTO_OTHER" | "TRIP_ROUTE_FILE" | "CHAT_IMAGE"
interface PresignUpload { uploadUrl: string; bucket: string; objectKey: string; expireSeconds: number }
interface ConfirmUpload { fileId: number; bucket: string; objectKey: string; uploadStatus: string }
interface PresignDownload { fileId: number; bucket: string; objectKey: string; downloadUrl: string; expireSeconds: number }
function contentType(fileName: string): string { const value=fileName.toLowerCase(); if(value.endsWith('.png'))return 'image/png'; if(value.endsWith('.webp'))return 'image/webp'; if(value.endsWith('.heic'))return 'image/heic'; if(value.endsWith('.heif'))return 'image/heif'; return 'image/jpeg' }
function fileName(path: string): string { const name=path.split('/').pop(); return name&&name.includes('.')?name:"upload-"+Date.now()+".jpg" }
function readFile(path: string): Promise<ArrayBuffer> { return new Promise((resolve,reject)=>wx.getFileSystemManager().readFile({filePath:path,success:result=>resolve(result.data as ArrayBuffer),fail:error=>reject(new Error(error.errMsg||"读取图片失败"))})) }
function put(url:string,data:ArrayBuffer,type:string):Promise<void>{return new Promise((resolve,reject)=>wx.request({url,method:"PUT",data,header:{"Content-Type":type},success:result=>{if(result.statusCode>=200&&result.statusCode<300)resolve();else reject(new Error("图片上传失败：HTTP "+result.statusCode))},fail:error=>reject(new Error(error.errMsg||"图片上传失败"))}))}
export async function uploadImage(path:string,bizType:ImageBizType,bizId=""):Promise<string>{const data=await readFile(path);if(!data.byteLength)throw new Error("图片内容为空");if(data.byteLength>10*1024*1024)throw new Error("单张图片不能超过10MB");const name=fileName(path);const type=contentType(name);const presign=await request<PresignUpload>("/v1/storage/presign-upload",{method:"POST",data:{fileName:name,contentType:type,fileSize:data.byteLength,bizType,bizId}});await put(presign.uploadUrl,data,type);const confirmed=await request<ConfirmUpload>("/v1/storage/confirm-upload",{method:"POST",data:{bucket:presign.bucket,objectKey:presign.objectKey,fileName:name,contentType:type,fileSize:data.byteLength,bizType,bizId}});return confirmed.objectKey}
export async function getImageUrl(objectKey:string):Promise<string>{if(!objectKey||objectKey.startsWith("http")||objectKey.startsWith("wxfile:"))return objectKey;const result=await request<PresignDownload>("/v1/storage/presign-download?objectKey="+encodeURIComponent(objectKey));return result.downloadUrl}
