<script setup>
import { onMounted, ref } from 'vue'
import { BadgePercent, Boxes, CircleDollarSign, Clock3, RefreshCw, Store, TicketCheck } from 'lucide-vue-next'
import { getOverview } from '../services/merchant.js'
const data = ref({}); const loading = ref(false); const error = ref('')
async function load() { loading.value = true; error.value = ''; try { data.value = await getOverview() } catch (e) { error.value = e.message } finally { loading.value = false } }
onMounted(load)
</script>
<template><div class="page"><div class="page-head"><div><small class="eyebrow">PARTNER WORKSPACE</small><h1>早上好，{{ data.merchantName || '合作伙伴' }}</h1><p>门店与优惠券经营数据来自本地 Spring Boot 服务。</p></div><button class="btn" :disabled="loading" @click="load"><RefreshCw :class="{ spin: loading }" />刷新数据</button></div><div v-if="error" class="notice danger">{{ error }}</div><div class="metric-grid"><article class="metric"><span><Store /></span><div><small>经营门店</small><b>{{ data.storeCount || 0 }}</b><em>家</em></div></article><article class="metric"><span><BadgePercent /></span><div><small>优惠券总数</small><b>{{ data.couponCount || 0 }}</b><em>张</em></div></article><article class="metric"><span><Clock3 /></span><div><small>待审核</small><b>{{ data.pendingCouponCount || 0 }}</b><em>项</em></div></article><article class="metric"><span><TicketCheck /></span><div><small>已上线</small><b>{{ data.onlineCouponCount || 0 }}</b><em>项</em></div></article></div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><h2>经营进度</h2><p>首期商业合作伙伴闭环</p></div><span class="tag success">{{ data.merchantLevel || 'STARTER' }}</span></div><div class="step-list"><div class="done"><b>1</b><span><strong>商家认证已通过</strong><small>已取得商家中心访问权限</small></span></div><div :class="{ done: data.storeCount > 0 }"><b>2</b><span><strong>创建经营门店</strong><small>完善地址、营业时间及停车信息</small></span></div><div :class="{ done: data.couponCount > 0 }"><b>3</b><span><strong>发布出行优惠</strong><small>平台审核后在 App 商家市场展示</small></span></div></div></section><section class="panel"><div class="panel-head"><div><h2>库存概况</h2><p>已售与可经营库存</p></div><Boxes /></div><div class="stock-card"><CircleDollarSign /><div><small>优惠券总库存</small><b>{{ data.totalStock || 0 }}</b></div></div><div class="stock-card soft"><TicketCheck /><div><small>累计售出</small><b>{{ data.soldCount || 0 }}</b></div></div></section></div></div></template>
