<script setup>
import { onMounted, reactive, ref } from 'vue'
import { Plus, TicketCheck } from 'lucide-vue-next'
import { createPartnerCoupon, getPartnerCoupons } from '../services/merchant.js'
const rows=ref([]),message=ref(''),open=ref(false)
const form=reactive({couponName:'免费洗车券',couponType:'CAR_WASH',sourceType:'PARTNER',discountAmount:50,discountRate:0,thresholdAmount:0,totalStock:100,validDays:30,settlementMode:'FREE_SPONSOR'})
async function load(){try{rows.value=await getPartnerCoupons()}catch(e){message.value=e.message}}
async function submit(){try{await createPartnerCoupon(form);open.value=false;message.value='合作券已提交平台审核';await load()}catch(e){message.value=e.message}}
onMounted(load)
</script>
<template><div class="page"><div class="page-head"><div><small class="eyebrow">PARTNER COUPON POOL</small><h1>合作商券</h1><p>创建免费券并提交真实库存，审核通过后进入平台合作券池。</p></div><button class="btn primary" @click="open=true"><Plus/>创建合作券</button></div><div v-if="message" class="notice">{{message}}</div><section class="panel"><div class="table-wrap"><table><thead><tr><th>券名称</th><th>类型</th><th>总库存</th><th>已发放</th><th>有效天数</th><th>审核</th></tr></thead><tbody><tr v-for="row in rows" :key="row.couponPoolId"><td><b>{{row.couponName}}</b><small>{{row.couponPoolId}}</small></td><td>{{row.couponType}}</td><td>{{row.totalStock}}</td><td>{{row.usedStock}}</td><td>{{row.validDays}}</td><td><span class="tag">{{row.auditStatus}}</span></td></tr><tr v-if="!rows.length"><td colspan="6">暂无合作券</td></tr></tbody></table></div></section><div v-if="open" class="modal-mask" @click.self="open=false"><form class="modal" @submit.prevent="submit"><div class="modal-head"><h2>创建免费合作券</h2></div><div class="form-grid"><label class="full"><span>券名称</span><input v-model="form.couponName" maxlength="128" required></label><label><span>券类型</span><select v-model="form.couponType"><option value="CAR_WASH">洗车券</option><option value="MAINTENANCE">保养抵扣券</option><option value="CASH">现金抵扣券</option></select></label><label><span>券面价值</span><input v-model.number="form.discountAmount" type="number" min="0.01" step="0.01" required></label><label><span>库存</span><input v-model.number="form.totalStock" type="number" min="1" step="1" required></label><label><span>领取后有效天数</span><input v-model.number="form.validDays" type="number" min="1" step="1" required></label></div><div class="modal-foot"><button type="button" class="btn" @click="open=false">取消</button><button class="btn primary"><TicketCheck/>提交审核</button></div></form></div></div></template>
