<script setup>
import { onMounted, reactive, ref } from 'vue'
import { Boxes, Plus } from 'lucide-vue-next'
import { createProduct, getProducts, offShelfProduct } from '../services/merchant.js'
const rows=ref([]),open=ref(false),message=ref('')
const form=reactive({productName:'',productType:'SERVICE',originalPrice:100,groupPrice:80,ladderPriceJson:'{}',targetPeople:2,stock:100,validHours:24,minSettlementPrice:0,imageKeys:[],description:''})
async function load(){try{const data=await getProducts();rows.value=data.records||[]}catch(e){message.value=e.message}}
async function submit(){try{await createProduct(form);open.value=false;await load()}catch(e){message.value=e.message}}
async function off(id){if(!confirm('确认下架该商品？'))return;try{await offShelfProduct(id);await load()}catch(e){message.value=e.message}}
onMounted(load)
</script>
<template><div class="page"><div class="page-head"><div><small class="eyebrow">PRODUCT CATALOG</small><h1>商品管理</h1><p>维护普通商户商品、价格和库存。</p></div><button class="btn primary" @click="open=true"><Plus/>发布商品</button></div><div v-if="message" class="notice danger">{{message}}</div><section class="panel"><div class="table-wrap"><table><thead><tr><th>商品</th><th>类型</th><th>原价/售价</th><th>库存</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.productId"><td><b>{{row.productName}}</b><small>{{row.description}}</small></td><td>{{row.productType}}</td><td>¥{{row.originalPrice}} / ¥{{row.groupPrice}}</td><td>{{row.stock}}</td><td><span class="tag">{{row.productStatus}}</span></td><td><button v-if="row.productStatus==='ON_SHELF'" class="btn sm danger" @click="off(row.productId)">下架</button></td></tr><tr v-if="!rows.length"><td colspan="6"><Boxes/>暂无商品</td></tr></tbody></table></div></section><div v-if="open" class="modal-mask" @click.self="open=false"><form class="modal" @submit.prevent="submit"><div class="modal-head"><h2>发布商品</h2></div><div class="form-grid"><label class="full"><span>商品名称</span><input v-model="form.productName" required maxlength="128"></label><label><span>商品类型</span><input v-model="form.productType" required maxlength="32"></label><label><span>原价</span><input v-model.number="form.originalPrice" type="number" min="0.01" required></label><label><span>销售价</span><input v-model.number="form.groupPrice" type="number" min="0.01" required></label><label><span>库存</span><input v-model.number="form.stock" type="number" min="0" required></label><label><span>有效小时</span><input v-model.number="form.validHours" type="number" min="1" required></label><label class="full"><span>商品说明</span><textarea v-model="form.description" maxlength="1000"></textarea></label></div><div class="modal-foot"><button type="button" class="btn" @click="open=false">取消</button><button class="btn primary">保存</button></div></form></div></div></template>
