<script setup>
import { onMounted, reactive, ref } from 'vue'
import { MapPin, Plus, RefreshCw, Store, X } from 'lucide-vue-next'
import { createStore, getStores } from '../services/merchant.js'
const rows = ref([]); const loading = ref(false); const open = ref(false); const message = ref('')
const form = reactive({ storeName: '', address: '', longitude: '113.2644', latitude: '23.1291', contactPhone: '', businessHours: '09:00-21:00', parkingInfo: '' })
async function load() { loading.value = true; try { rows.value = await getStores() } catch (e) { message.value = e.message } finally { loading.value = false } }
async function submit() { message.value = ''; try { await createStore({ ...form, longitude: Number(form.longitude), latitude: Number(form.latitude) }); open.value = false; await load() } catch (e) { message.value = e.message } }
onMounted(load)
</script>
<template><div class="page"><div class="page-head"><div><small class="eyebrow">STORE NETWORK</small><h1>门店管理</h1><p>维护线下经营地址，优惠券发布时必须关联当前商家的门店。</p></div><div class="actions"><button class="btn" @click="load"><RefreshCw :class="{ spin: loading }" />刷新</button><button class="btn primary" @click="open = true"><Plus />新增门店</button></div></div><div v-if="message" class="notice danger">{{ message }}</div><div v-if="!loading && !rows.length" class="empty"><Store /><h2>还没有经营门店</h2><p>先创建一个门店，再发布优惠券。</p><button class="btn primary" @click="open = true"><Plus />新增门店</button></div><div v-else class="card-grid"><article v-for="row in rows" :key="row.storeId" class="store-card"><div class="store-cover"><Store /><span class="tag success">{{ row.storeStatus }}</span></div><div class="store-body"><small>门店 ID {{ row.storeId }}</small><h2>{{ row.storeName }}</h2><p><MapPin />{{ row.address }}</p><dl><div><dt>营业时间</dt><dd>{{ row.businessHours }}</dd></div><div><dt>联系电话</dt><dd>{{ row.contactPhoneMask }}</dd></div><div><dt>停车信息</dt><dd>{{ row.parkingInfo || '暂未填写' }}</dd></div></dl></div></article></div><div v-if="open" class="modal-mask" @click.self="open = false"><form class="modal" @submit.prevent="submit"><div class="modal-head"><div><h2>新增经营门店</h2><p>坐标暂由商家填写，后续可接地图选点。</p></div><button type="button" class="plain-icon" @click="open = false"><X /></button></div><div class="form-grid"><label><span>门店名称</span><input v-model="form.storeName" required maxlength="128"></label><label><span>联系电话</span><input v-model="form.contactPhone" required maxlength="11"></label><label class="full"><span>详细地址</span><input v-model="form.address" required maxlength="255"></label><label><span>经度</span><input v-model="form.longitude" required type="number" step="0.000001"></label><label><span>纬度</span><input v-model="form.latitude" required type="number" step="0.000001"></label><label><span>营业时间</span><input v-model="form.businessHours" required></label><label><span>停车信息</span><input v-model="form.parkingInfo"></label></div><div class="modal-foot"><button type="button" class="btn" @click="open = false">取消</button><button class="btn primary">保存门店</button></div></form></div></div></template>
