create table if not exists order_trade (
    id bigint not null comment '记录主键',
    order_no varchar(64) not null comment '订单编号',
    user_id bigint not null comment '平台用户ID',
    merchant_id bigint not null default 0 comment '商家ID',
    product_id bigint not null comment '商品ID',
    activity_id bigint null comment '活动ID',
    original_amount decimal(12,2) not null default 0.00 comment '原始金额',
    groupbuy_discount_amount decimal(12,2) not null default 0.00 comment '拼团优惠金额',
    coupon_deduction_amount decimal(12,2) not null default 0.00 comment '优惠券抵扣金额',
    payable_amount decimal(12,2) not null default 0.00 comment '应付金额',
    paid_amount decimal(12,2) not null default 0.00 comment '支付金额',
    user_coupon_id bigint null comment '用户优惠券ID',
    order_status varchar(32) not null comment '订单状态',
    payment_status varchar(32) not null comment '支付状态',
    verification_status varchar(32) not null comment '核销状态',
    refund_status varchar(32) not null comment '退款状态',
    profit_sharing_status varchar(32) not null comment '分账分账状态',
    expire_at datetime null comment '过期时间',
    paid_at datetime null comment '支付时间',
    completed_at datetime null comment '完成时间',
    remark varchar(255) not null default '' comment '业务备注',
    created_at datetime not null comment '记录创建时间',
    updated_at datetime not null comment '记录最后更新时间',
    deleted tinyint not null default 0 comment '逻辑删除标记：0未删除、1已删除',
    primary key (id),
    unique key uk_order_trade_no (order_no),
    key idx_order_trade_user (user_id, created_at),
    key idx_order_trade_merchant (merchant_id, created_at),
    key idx_order_trade_status (order_status, payment_status),
    key idx_order_trade_activity (activity_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='订单交易表';

create table if not exists order_item (
    id bigint not null comment '记录主键',
    order_id bigint not null comment '订单ID',
    product_id bigint not null comment '商品ID',
    product_name varchar(128) not null comment '商品名称',
    product_type varchar(32) not null comment '商品类型',
    unit_price decimal(12,2) not null default 0.00 comment '商品单价',
    quantity int not null default 1 comment '数量',
    total_amount decimal(12,2) not null default 0.00 comment '总计金额',
    snapshot_json text null comment '业务快照JSON数据',
    created_at datetime not null comment '记录创建时间',
    primary key (id),
    key idx_order_item_order (order_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='订单事项表';

create table if not exists order_compensation_task (
    id bigint not null comment '记录主键',
    biz_type varchar(64) not null comment '关联业务类型',
    biz_id varchar(64) not null comment '关联业务单据标识',
    idempotent_key varchar(128) not null comment '业务幂等键，用于防止重复处理',
    target_module varchar(64) not null comment '目标模块',
    request_payload text null comment '任务请求参数载荷',
    task_status varchar(32) not null comment '任务状态',
    retry_count int not null default 0 comment '任务已重试次数',
    next_retry_at datetime null comment '下一次计划重试时间',
    last_error varchar(1000) null comment '最后一次执行错误信息',
    created_at datetime not null comment '记录创建时间',
    updated_at datetime not null comment '记录最后更新时间',
    primary key (id),
    key idx_order_compensation_status (task_status, next_retry_at),
    key idx_order_compensation_biz (biz_type, biz_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='订单补偿任务表';
