<script setup>
import { onMounted, ref } from 'vue'
import { LoaderCircle, MessageSquareWarning, RefreshCw, ShieldCheck } from 'lucide-vue-next'
import { listChatReports, listMessageRisks, listTripConfirmations, reviewChatReport } from '../services/chatRisk.js'
import { showToast } from '../utils.js'
const reports=ref([]),risks=ref([]),confirmations=ref([]),loading=ref(false),tab=ref('reports'),status=ref('PENDING')
async function load(){loading.value=true;try{reports.value=await listChatReports(status.value)||[];risks.value=await listMessageRisks(status.value)||[];confirmations.value=await listTripConfirmations(status.value==='PENDING'?'OPEN':status.value)||[]}catch(e){showToast(e.message,'error')}finally{loading.value=false}}
async function review(row,decision){const note=window.prompt('请输入审核说明');if(!note?.trim())return;try{await reviewChatReport(row.id,decision,note.trim());showToast('举报处理完成');await load()}catch(e){showToast(e.message,'error')}}
onMounted(load)
</script>
<template><div class="page"><div class="page-head"><div><div class="eyebrow"><MessageSquareWarning/> CHAT SAFETY</div><h1>聊天风控</h1><p>查看用户举报与敏感消息风险，所有人工处理均使用 Admin 登录身份。</p></div><button class="btn" @click="load"><LoaderCircle v-if="loading" class="spin"/><RefreshCw v-else/>刷新</button></div>
<div class="tabs"><button class="tab" :class="{active:tab==='reports'}" @click="tab='reports'">用户举报</button><button class="tab" :class="{active:tab==='risks'}" @click="tab='risks'">敏感消息</button><button class="tab" :class="{active:tab==='confirmations'}" @click="tab='confirmations'">行程确认</button></div>
<section class="panel" style="margin-top:16px"><div class="panel-head"><div><h2>{{tab==='reports'?'举报审核队列':tab==='risks'?'消息风险队列':'行程确认监控'}}</h2><p>运营端仅查看状态，不代替队长或成员确认</p></div><select v-model="status" class="field" @change="load"><option value="PENDING">待处理 / 进行中</option><option value="">全部</option></select></div>
<div v-if="tab==='reports'" class="table-wrap"><table><thead><tr><th>举报 / 群聊</th><th>举报人</th><th>目标</th><th>类型与原因</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in reports" :key="row.id"><td><b>#{{row.id}}</b><small>群聊 {{row.conversationId}}</small></td><td>{{row.reporterUserId}}</td><td>{{row.targetType}} / {{row.targetId}}</td><td>{{row.reportType}}<small>{{row.reason}}</small></td><td><span class="status warning">{{row.reportStatus}}</span></td><td><button class="btn sm success" @click="review(row,'RESOLVED')">确认处置</button><button class="btn sm" @click="review(row,'REJECTED')">不成立</button><button class="btn sm danger" @click="review(row,'FLAGGED')">风险标记</button></td></tr></tbody></table></div>
<div v-else-if="tab==='risks'" class="table-wrap"><table><thead><tr><th>风险 / 消息</th><th>群聊 / 发送人</th><th>风险类型</th><th>置信度</th><th>规则</th><th>状态</th></tr></thead><tbody><tr v-for="row in risks" :key="row.id"><td><b>#{{row.id}}</b><small>消息 {{row.messageId}}</small></td><td>{{row.conversationId}} / {{row.senderUserId}}</td><td>{{row.riskLevel}} · {{row.riskType}}</td><td>{{row.confidence}}%</td><td>{{row.matchedRule}}</td><td><span class="status danger">{{row.status}}</span></td></tr></tbody></table></div>
<div v-else class="table-wrap"><table><thead><tr><th>确认单 / 行程</th><th>群聊</th><th>队长</th><th>已确认</th><th>待回复</th><th>不参加</th><th>状态</th></tr></thead><tbody><tr v-for="row in confirmations" :key="row.id"><td><b>{{row.tripName||'#'+row.tripId}}</b><small>确认单 {{row.id}}</small></td><td>{{row.conversationId}}</td><td>{{row.creatorUserId}}</td><td>{{row.confirmedCount}} / {{row.memberCount}}</td><td>{{row.waitingCount}}</td><td>{{row.rejectedCount}}</td><td><span class="status" :class="row.confirmationStatus==='OPEN'?'warning':'success'">{{row.confirmationStatus}}</span></td></tr></tbody></table></div>
<div v-if="(tab==='reports'&&!reports.length)||(tab==='risks'&&!risks.length)||(tab==='confirmations'&&!confirmations.length)" class="empty-note"><ShieldCheck/><p>当前没有对应记录</p></div></section></div></template>
