<script setup>
import { onMounted, reactive, ref } from 'vue'
import { BadgeCheck, Clock3, LoaderCircle, RefreshCw, Search, Store, XCircle } from 'lucide-vue-next'
import BaseModal from '../components/BaseModal.vue'
import { auditMerchantApplication, getMerchantApplication, getMerchantApplications } from '../services/merchantAudit.js'
import { showToast } from '../utils.js'
const rows = ref([]); const total = ref(0); const loading = ref(false); const selected = ref(null); const open = ref(false); const reason = ref(''); const processing = ref(false)
const filters = reactive({ status: 'PENDING', page: 1, size: 20 })
const meta = s => ({ PENDING: ['待办理','warning'], APPROVED: ['已同意','success'], REJECTED: ['已拒绝','danger'] }[s] || [s,''])
async function load() { loading.value = true; try { const data = await getMerchantApplications(filters); rows.value = data.records || []; total.value = Number(data.total || 0) } catch(e){ showToast(e.message) } finally { loading.value = false } }
async function detail(row) { open.value = true; selected.value = row; reason.value = row.rejectReason || ''; try { selected.value = await getMerchantApplication(row.merchantId) } catch(e){ showToast(e.message) } }
async function audit(result) { if (result === 'REJECTED' && reason.value.trim().length < 2) return showToast('拒绝时请填写至少 2 个字的原因'); processing.value = true; try { await auditMerchantApplication(selected.value.merchantId, result, reason.value.trim()); showToast(result === 'APPROVED' ? '商家已同意并授予商家权限' : '商家申请已拒绝'); open.value = false; await load() } catch(e){ showToast(e.message) } finally { processing.value = false } }
onMounted(load)
</script>
<template><div class="page"><div class="page-head"><div><div class="eyebrow"><Store /> MERCHANT ONBOARDING</div><h1>商家入驻审核</h1><p>审核 App 提交的主体、门店、法人和行业资质；通过后账号获得商家后台权限。</p></div><button class="btn" @click="load"><LoaderCircle v-if="loading" class="spin"/><RefreshCw v-else/>刷新队列</button></div><div class="grid cols-3 audit-metrics"><div class="metric compact-metric"><Clock3/><span><small>当前筛选</small><b>{{ total }}</b></span></div><div class="metric compact-metric"><BadgeCheck/><span><small>权限授予</small><b>自动</b></span></div><div class="metric compact-metric danger"><XCircle/><span><small>驳回可重提</small><b>支持</b></span></div></div><section class="panel"><div class="panel-head"><div><h2>入驻申请</h2><p>办理状态实时写回 App 与商家中心</p></div><span class="endpoint">GET /v1/admin/merchants/applications</span></div><div class="toolbar"><select v-model="filters.status" class="field" @change="load"><option value="">全部状态</option><option value="PENDING">待办理</option><option value="APPROVED">已同意</option><option value="REJECTED">已拒绝</option></select><button class="btn primary" @click="load"><Search/>查询</button></div><div v-if="!rows.length" class="empty-note"><Store/><p>当前状态下没有商家申请</p></div><div v-else class="table-wrap"><table><thead><tr><th>商家 / ID</th><th>经营类目</th><th>提交时间</th><th>审核状态</th><th>拒绝原因</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.merchantId"><td><b>{{ row.merchantName }}</b><small>{{ row.merchantId }}</small></td><td>{{ row.category }}</td><td>{{ row.submittedAt || '—' }}</td><td><span class="status" :class="meta(row.auditStatus)[1]">{{ meta(row.auditStatus)[0] }}</span></td><td>{{ row.rejectReason || '—' }}</td><td><button class="btn sm" @click="detail(row)">{{ row.auditStatus === 'PENDING' ? '办理' : '查看' }}</button></td></tr></tbody></table></div></section><BaseModal :open="open" title="商家入驻资料" @close="open=false"><template v-if="selected"><div class="detail-grid"><div class="detail-item"><small>商家名称</small><b>{{ selected.merchantName }}</b></div><div class="detail-item"><small>经营类目</small><b>{{ selected.category }}</b></div><div class="detail-item"><small>商家等级</small><b>{{ selected.merchantLevel || '待授予' }}</b></div><div class="detail-item"><small>当前状态</small><b>{{ meta(selected.auditStatus)[0] }}</b></div></div><pre class="code-note">{{ JSON.stringify(selected.applicationDetails || {}, null, 2) }}</pre><div v-if="selected.auditStatus === 'PENDING'" class="form-group"><label>拒绝原因（拒绝时必填）</label><textarea v-model="reason" class="field" maxlength="255"></textarea></div></template><template #footer><button class="btn" @click="open=false">关闭</button><template v-if="selected?.auditStatus === 'PENDING'"><button class="btn danger" :disabled="processing" @click="audit('REJECTED')">拒绝</button><button class="btn success solid" :disabled="processing" @click="audit('APPROVED')">同意</button></template></template></BaseModal></div></template>
