<script setup>
import { computed, ref } from 'vue'
import { History, Ticket, TrendingUp, UserPlus } from 'lucide-vue-next'
import { showToast } from '../utils.js'

const active=ref('growth')
const configs={
  growth:{label:'成长规则',icon:TrendingUp,domain:'GROWTH',key:'growth.rules',version:'13',endpoint:'/v1/admin/growth-rules',request:'growth-rule-v14-20260720',reason:'对齐MVP勋章自动授予口径',json:'{\n  "tripCompleted": 100,\n  "mileagePointsPer100Km": 10,\n  "badgeEvaluation": "AUTO_AFTER_GRANT",\n  "badgeRules": ["FIRST_DEPARTURE", "DISTANCE_100KM", "DISTANCE_1000KM", "DISTANCE_10000KM", "INVITE_10", "INVITE_50"]\n}'},
  invite:{label:'邀请规则',icon:UserPlus,domain:'INVITE',key:'invite.rules',version:'9',endpoint:'/v1/admin/invite-rules',request:'invite-rule-v10-20260720',reason:'对齐七天轮换邀请二维码与奖励字段',json:'{\n  "registerPoints": 100,\n  "firstTeamPoints": 100,\n  "stagePoints": {"3": 200, "10": 500, "30": 2000, "50": 5000},\n  "qrRotationDays": 7,\n  "qrSignature": "HMAC_SHA256"\n}'},
  coupon:{label:'优惠券预算',icon:Ticket,domain:'COUPON',key:'coupon.budgets',version:'6',endpoint:'/v1/admin/coupon-budgets',request:'coupon-budget-v7-20260713',reason:'暑期券预算调整',json:'{\n  "totalBudget": 200000,\n  "perUserLimit": 5,\n  "alertThreshold": 0.8\n}'},
  history:{label:'版本记录',icon:History,domain:'CONFIG',key:'version.history',version:'-',endpoint:'/v1/admin/audit-logs?targetModule=CONFIG',request:'-',reason:'查询平台规则的历史发布记录',json:'{\n  "message": "版本记录由审计日志提供"\n}'},
}
const config=computed(()=>configs[active.value])
</script>

<template><div class="page"><div class="page-head"><div><h1>运营规则配置</h1><p>成长、邀请和优惠券预算配置的版本化管理</p></div><div class="head-actions"><button class="btn" @click="active='history'">查看版本历史</button><button class="btn primary" @click="showToast('配置草稿已保存')">保存草稿</button></div></div>
  <div class="config-layout"><div class="panel config-nav"><div v-for="(item,id) in configs" :key="id" class="config-item" :class="{active:active===id}" @click="active=id"><component :is="item.icon" />{{item.label}}</div></div><div class="panel"><div class="panel-head"><div><h2>{{config.label}} · {{config.key}}</h2><p>当前版本 V{{config.version}} · ACTIVE</p></div><span class="endpoint">GET {{config.endpoint}}</span></div><div class="panel-body"><div class="notice-box">更新配置会生成新版本并写入审计日志；effectiveAt 为空时立即生效。</div><div class="form-grid" style="margin-top:16px"><div class="form-group"><label>配置域</label><input class="field" :value="config.domain" disabled></div><div class="form-group"><label>配置键</label><input class="field" :value="config.key"></div><div class="form-group"><label>当前版本</label><input class="field" :value="config.version" disabled></div><div class="form-group"><label>生效时间</label><input class="field" type="datetime-local" value="2026-07-14T00:00"></div><div class="form-group full"><label>配置值（JSON 字符串）</label><textarea class="field" :value="config.json"></textarea></div><div class="form-group"><label>操作人 ID</label><input class="field" value="10001"></div><div class="form-group"><label>请求幂等 ID</label><input class="field" :value="config.request"></div><div class="form-group full"><label>变更原因</label><input class="field" :value="config.reason"></div></div><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:16px"><button class="btn" @click="showToast('JSON 格式校验通过')">JSON 校验</button><button class="btn primary" @click="showToast(config.label+'新版本已提交（原型）')">发布新版本</button></div><div class="code-note" style="margin-top:14px">PUT {{config.endpoint}} · AdminConfigUpdateRequest</div></div></div></div>
  <div class="grid cols-3" style="margin-top:16px"><div class="api-card"><div class="api-card-top"><b>勋章触发</b><span class="status success">自动</span></div><div class="api-path">growth_badge.event_type + threshold</div><p>成长流水提交成功后立即计算真实指标并幂等授予，App 不提供手动领取。</p></div><div class="api-card"><div class="api-card-top"><b>邀请二维码</b><span class="status info">7 天</span></div><div class="api-path">GET /v1/invites/me/qr</div><p>邀请码保持稳定，二维码签名令牌按七天时间窗自动轮换，可验签和识别过期。</p></div><div class="api-card"><div class="api-card-top"><b>配置审计</b><span class="method">GET</span></div><div class="api-path">/v1/admin/audit-logs?targetModule=CONFIG</div><p>追踪版本发布人、原因与操作结果。</p></div></div>
</div></template>
