<script setup>
import { computed, ref } from 'vue'
import { Landmark, ShoppingBag, Undo2, WalletCards } from 'lucide-vue-next'
import BaseModal from '../components/BaseModal.vue'
import MetricCard from '../components/MetricCard.vue'
import { showToast } from '../utils.js'

const active=ref('orders'), keyword=ref(''), modal=ref(false), modalTitle=ref('交易详情')
const metrics=[['今日订单','428','↑ 18.2%',ShoppingBag,false],['实付金额','¥36,820','客单价 ¥86.03',WalletCards,false],['待审退款','3','最长等待 18 分钟',Undo2,true],['待结算','¥12,540','共 16 笔',Landmark,false]]
const orders=[['TLX2026071300821','林宇','同路洗车 · 精洗服务','¥128','¥30','¥98','14:32','已支付','success'],['TLX2026071300818','陈晓','川途营地 · 营位券','¥260','¥50','¥210','13:48','已核销','info'],['TLX2026071300806','周明','悦行维修 · 基础保养','¥399','¥0','¥399','12:05','待支付','warning']]
const shownOrders=computed(()=>orders.filter(row=>row.join(' ').toLowerCase().includes(keyword.value.toLowerCase())))
function switchTab(id){active.value=id;keyword.value=''} function open(title){modalTitle.value=title;modal.value=true} function action(text){modal.value=false;showToast(text)}
</script>

<template><div class="page"><div class="page-head"><div><h1>交易管理</h1><p>订单、退款、结算与核销撤销的一体化处理台</p></div><div class="head-actions"><button class="btn" @click="showToast('流水导出任务已创建（原型）')">导出流水</button><button class="btn primary" @click="showToast('交易数据已刷新')">刷新数据</button></div></div>
  <div class="grid cols-4"><MetricCard v-for="m in metrics" :key="m[0]" :label="m[0]" :value="m[1]" :trend="m[2]" :icon="m[3]" :down="m[4]" /></div>
  <div class="tabs" style="margin-top:16px"><button v-for="t in [{id:'orders',n:'订单'},{id:'refunds',n:'退款审核'},{id:'settlements',n:'结算'},{id:'reversals',n:'核销撤销'}]" :key="t.id" class="tab" :class="{active:active===t.id}" @click="switchTab(t.id)">{{t.n}}</button></div>
  <div v-if="active==='orders'" style="margin-top:12px"><div class="notice-box" style="margin-bottom:12px">AdminOrderController 当前返回 order-module 占位空分页；下表用于定义接入真实查询端口后的管理端字段。</div><div class="panel"><div class="toolbar"><input v-model="keyword" class="field search" placeholder="订单号 / 用户 / 商家"><select class="field"><option>全部状态</option><option>WAIT_PAY</option><option>PAID</option><option>VERIFIED</option><option>CLOSED</option></select><input class="field" type="date"><button class="btn primary">查询</button><span class="endpoint">GET /v1/admin/orders</span></div><div class="table-wrap"><table><thead><tr><th>订单号</th><th>用户</th><th>商家 / 商品</th><th>原价</th><th>优惠</th><th>实付</th><th>创建时间</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in shownOrders" :key="row[0]"><td v-for="cell in row.slice(0,7)" :key="cell">{{cell}}</td><td><span class="status" :class="row[8]">{{row[7]}}</span></td><td><button class="btn sm" @click="open('订单详情 · '+row[0])">详情</button></td></tr></tbody></table></div><div class="pagination"><span>原型数据 3 条</span><div class="pages"><span class="page-no active">1</span></div></div></div></div>
  <div v-else-if="active==='refunds'" style="margin-top:12px"><div class="panel"><div class="toolbar"><input class="field search" placeholder="退款单 / 订单号"><select class="field"><option>待审核</option><option>已通过</option><option>已拒绝</option></select><span class="endpoint">GET /v1/admin/refunds</span></div><div class="table-wrap"><table><thead><tr><th>退款单</th><th>订单</th><th>申请人</th><th>金额</th><th>原因</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in [['RF20260713031','TLX...0821','林宇','¥98','商家无法履约'],['RF20260713028','TLX...0782','王凯','¥68','行程变更']]" :key="row[0]"><td v-for="cell in row" :key="cell">{{cell}}</td><td><span class="status warning">待审核</span></td><td><button class="btn sm" @click="open('退款审核 · '+row[0])">审核</button></td></tr></tbody></table></div></div></div>
  <div v-else-if="active==='settlements'" style="margin-top:12px"><div class="panel"><div class="toolbar"><select class="field"><option>待结算</option><option>处理中</option><option>已完成</option></select><span class="endpoint">GET /v1/admin/settlements</span></div><div class="table-wrap"><table><thead><tr><th>结算单</th><th>商家</th><th>交易额</th><th>佣金</th><th>应结算</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>ST20260713012</td><td>同路洗车</td><td>¥8,620</td><td>¥862</td><td>¥7,758</td><td><span class="status warning">待触发</span></td><td><button class="btn sm primary" @click="showToast('已触发结算处理（原型）')">触发结算</button></td></tr><tr><td>ST20260713009</td><td>川途营地</td><td>¥5,440</td><td>¥544</td><td>¥4,896</td><td><span class="status info">处理中</span></td><td><button class="btn sm" @click="open('结算详情 · ST20260713009')">详情</button></td></tr></tbody></table></div></div></div>
  <div v-else style="margin-top:12px"><div class="panel"><div class="toolbar"><select class="field"><option>待审核</option><option>已通过</option></select><span class="endpoint">GET /v1/admin/verifications/reversals</span></div><div class="table-wrap"><table><thead><tr><th>撤销申请</th><th>核销记录</th><th>商家</th><th>原因</th><th>申请时间</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>VR20260713005</td><td>VER-892311</td><td>同路洗车</td><td>门店误核销</td><td>14:10</td><td><span class="status warning">待审核</span></td><td><button class="btn sm" @click="open('核销撤销审核 · VR20260713005')">审核</button></td></tr></tbody></table></div></div></div>
  <BaseModal :open="modal" :title="modalTitle" @close="modal=false"><div class="detail-grid"><div class="detail-item"><small>目标模块</small><b>payment-module</b></div><div class="detail-item"><small>请求幂等 ID</small><b>admin-20260713-031</b></div><div class="detail-item"><small>处理状态</small><b>PROCESSING</b></div><div class="detail-item"><small>操作人</small><b>10001</b></div></div><div class="form-group" style="margin-top:14px"><label>审核/处理原因</label><textarea class="field" style="height:80px"></textarea></div><div class="code-note">POST /v1/admin/refunds/{refundId}/audit
POST /v1/admin/settlements/{settlementId}/trigger
POST /v1/admin/verifications/reversals/{reversalId}/audit</div><template #footer><button class="btn" @click="modal=false">取消</button><button class="btn danger" @click="action('已拒绝（原型）')">拒绝</button><button class="btn primary" @click="action('已提交处理（原型）')">确认</button></template></BaseModal>
</div></template>
