CREATE TABLE IF NOT EXISTS driver_track_record (
    id BIGINT PRIMARY KEY comment '记录主键',
    trip_id BIGINT NOT NULL comment '行程ID',
    driver_id BIGINT NOT NULL comment '驾驶人ID',
    longitude DECIMAL(10,6) NOT NULL comment '经度坐标',
    latitude DECIMAL(10,6) NOT NULL comment '纬度坐标',
    altitude DECIMAL(10,2) NULL comment '海拔',
    speed DECIMAL(10,2) NULL comment '速度',
    direction DECIMAL(10,2) NULL comment '方向',
    accuracy DECIMAL(10,2) NOT NULL comment '定位精度',
    raw_distance_from_prev INT NOT NULL DEFAULT 0 comment '原始与上一轨迹点的距离',
    distance_from_prev INT NOT NULL DEFAULT 0 comment '与上一轨迹点的距离',
    calculated_speed_kmh DECIMAL(10,2) NOT NULL DEFAULT 0 comment '计算速度，单位为公里每小时',
    provider VARCHAR(16) NOT NULL DEFAULT 'fused' comment '数据或服务提供方',
    app_state VARCHAR(16) NOT NULL DEFAULT 'foreground' comment '应用状态',
    battery_level INT NULL comment '设备剩余电量百分比',
    device_id VARCHAR(128) NULL comment '设备ID',
    sequence_no BIGINT NOT NULL comment '序号编号',
    mock_location TINYINT NOT NULL DEFAULT 0 comment '是否疑似模拟定位：0否、1是',
    point_status VARCHAR(32) NOT NULL DEFAULT 'ACCEPTED' comment '轨迹点状态',
    valid_point TINYINT NOT NULL DEFAULT 1 comment '是否为有效轨迹点：0否、1是',
    risk_score INT NOT NULL DEFAULT 0 comment '风险评分',
    risk_flags VARCHAR(255) NULL comment '风险标记集合',
    reject_reason VARCHAR(255) NULL comment '驳回原因',
    record_time DATETIME NOT NULL comment '记录时间',
    client_send_time DATETIME NULL comment '客户端发送时间',
    server_receive_time DATETIME NOT NULL comment '服务端接收时间',
    created_at DATETIME NOT NULL comment '记录创建时间',
    deleted TINYINT NOT NULL DEFAULT 0 comment '逻辑删除标记：0未删除、1已删除',
    UNIQUE KEY uk_driver_track_sequence (trip_id, driver_id, sequence_no, deleted),
    KEY idx_driver_track_trip_time (trip_id, record_time),
    KEY idx_driver_track_driver_time (driver_id, record_time),
    KEY idx_driver_track_status (trip_id, point_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='驾驶人轨迹记录表';

CREATE TABLE IF NOT EXISTS driver_track_distance_record (
    id BIGINT PRIMARY KEY comment '记录主键',
    trip_id BIGINT NOT NULL comment '行程ID',
    driver_id BIGINT NOT NULL comment '驾驶人ID',
    total_distance INT NOT NULL DEFAULT 0 comment '总计距离',
    last_settle_distance INT NOT NULL DEFAULT 0 comment '最后结算距离',
    settle_type VARCHAR(32) NOT NULL comment '结算类型',
    settle_key VARCHAR(128) NOT NULL comment '结算标识或存储Key',
    settle_time DATETIME NOT NULL comment '结算时间',
    event_published TINYINT NOT NULL DEFAULT 0 comment '相关业务事件是否已发布：0否、1是',
    created_at DATETIME NOT NULL comment '记录创建时间',
    updated_at DATETIME NOT NULL comment '记录最后更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 comment '逻辑删除标记：0未删除、1已删除',
    UNIQUE KEY uk_driver_track_distance_settle_key (settle_key, deleted),
    KEY idx_driver_track_distance_trip_driver (trip_id, driver_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='驾驶人轨迹距离记录表';

CREATE TABLE IF NOT EXISTS driver_track_deviation_record (
    id BIGINT PRIMARY KEY comment '记录主键',
    trip_id BIGINT NOT NULL comment '行程ID',
    driver_id BIGINT NOT NULL comment '驾驶人ID',
    longitude DECIMAL(10,6) NOT NULL comment '经度坐标',
    latitude DECIMAL(10,6) NOT NULL comment '纬度坐标',
    deviation_distance INT NOT NULL DEFAULT 0 comment '偏离距离',
    deviation_status TINYINT NOT NULL DEFAULT 0 comment '偏离状态',
    record_time DATETIME NOT NULL comment '记录时间',
    created_at DATETIME NOT NULL comment '记录创建时间',
    deleted TINYINT NOT NULL DEFAULT 0 comment '逻辑删除标记：0未删除、1已删除',
    KEY idx_driver_track_deviation_trip_driver_time (trip_id, driver_id, record_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='驾驶人轨迹偏离记录表';

CREATE TABLE IF NOT EXISTS trip_member_latest_location (
    id BIGINT PRIMARY KEY comment '记录主键',
    trip_id BIGINT NOT NULL comment '行程ID',
    captain_user_id BIGINT NOT NULL comment '队长用户ID',
    member_user_id BIGINT NOT NULL comment '普通成员用户ID',
    longitude DECIMAL(10,6) NOT NULL comment '成员最新经度',
    latitude DECIMAL(10,6) NOT NULL comment '成员最新纬度',
    speed DECIMAL(10,2) NULL comment '成员上报速度',
    accuracy DECIMAL(10,2) NOT NULL comment '定位精度',
    sequence_no BIGINT NOT NULL comment '客户端递增序号',
    mock_location TINYINT NOT NULL DEFAULT 0 comment '是否疑似模拟定位',
    record_time DATETIME NOT NULL comment '客户端实际采集时间',
    server_receive_time DATETIME NOT NULL comment '服务端接收时间',
    created_at DATETIME NOT NULL comment '记录创建时间',
    updated_at DATETIME NOT NULL comment '记录最后更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 comment '逻辑删除标记',
    UNIQUE KEY uk_trip_member_latest_location (trip_id, member_user_id, deleted),
    KEY idx_trip_member_location_time (trip_id, record_time),
    KEY idx_trip_member_location_captain (captain_user_id, record_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='普通成员最新位置快照表';

CREATE TABLE IF NOT EXISTS trip_track_summary (
    id BIGINT PRIMARY KEY comment '记录主键',
    trip_id BIGINT NOT NULL comment '行程ID',
    primary_user_id BIGINT NOT NULL comment '主要用户ID',
    raw_distance_meters INT NOT NULL DEFAULT 0 comment '原始距离，单位为米',
    filtered_distance_meters INT NOT NULL DEFAULT 0 comment '过滤后距离，单位为米',
    approved_distance_meters INT NOT NULL DEFAULT 0 comment '审核认可距离，单位为米',
    total_point_count INT NOT NULL DEFAULT 0 comment '总计轨迹点数量',
    valid_point_count INT NOT NULL DEFAULT 0 comment '有效轨迹点数量',
    invalid_point_count INT NOT NULL DEFAULT 0 comment '无效轨迹点数量',
    location_gap_count INT NOT NULL DEFAULT 0 comment '位置差值数量',
    warning_count INT NOT NULL DEFAULT 0 comment '警告数量',
    hard_anomaly_count INT NOT NULL DEFAULT 0 comment '严重异常数量',
    risk_score INT NOT NULL DEFAULT 0 comment '风险评分',
    risk_level VARCHAR(16) NOT NULL DEFAULT 'LOW' comment '风险等级',
    settlement_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' comment '结算状态',
    review_reason VARCHAR(255) NULL comment '审核原因',
    reviewer_id BIGINT NULL comment '审核人ID',
    reviewed_at DATETIME NULL comment '审核时间',
    created_at DATETIME NOT NULL comment '记录创建时间',
    updated_at DATETIME NOT NULL comment '记录最后更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 comment '逻辑删除标记：0未删除、1已删除',
    UNIQUE KEY uk_trip_track_summary_trip (trip_id, deleted),
    KEY idx_trip_track_summary_risk (risk_level, settlement_status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='行程轨迹汇总表';

CREATE TABLE IF NOT EXISTS trip_track_anomaly (
    id BIGINT PRIMARY KEY comment '记录主键',
    trip_id BIGINT NOT NULL comment '行程ID',
    user_id BIGINT NOT NULL comment '平台用户ID',
    previous_point_id BIGINT NULL comment '上一点轨迹点ID',
    current_point_id BIGINT NULL comment '当前轨迹点ID',
    anomaly_type VARCHAR(64) NOT NULL comment '异常类型',
    risk_score INT NOT NULL DEFAULT 0 comment '风险评分',
    detail_json JSON NULL comment '业务详情JSON数据',
    occurred_at DATETIME NOT NULL comment '发生时间',
    created_at DATETIME NOT NULL comment '记录创建时间',
    KEY idx_trip_track_anomaly_trip_time (trip_id, occurred_at),
    KEY idx_trip_track_anomaly_user_time (user_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='行程轨迹异常表';
