CREATE TABLE IF NOT EXISTS driver_track_record (
    id BIGINT PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    longitude DECIMAL(10,6) NOT NULL,
    latitude DECIMAL(10,6) NOT NULL,
    altitude DECIMAL(10,2) NULL,
    speed DECIMAL(10,2) NULL,
    direction DECIMAL(10,2) NULL,
    accuracy DECIMAL(10,2) NOT NULL,
    raw_distance_from_prev INT NOT NULL DEFAULT 0,
    distance_from_prev INT NOT NULL DEFAULT 0,
    calculated_speed_kmh DECIMAL(10,2) NOT NULL DEFAULT 0,
    provider VARCHAR(16) NOT NULL DEFAULT 'fused',
    app_state VARCHAR(16) NOT NULL DEFAULT 'foreground',
    battery_level INT NULL,
    device_id VARCHAR(128) NULL,
    sequence_no BIGINT NOT NULL,
    mock_location TINYINT NOT NULL DEFAULT 0,
    point_status VARCHAR(32) NOT NULL DEFAULT 'ACCEPTED',
    valid_point TINYINT NOT NULL DEFAULT 1,
    risk_score INT NOT NULL DEFAULT 0,
    risk_flags VARCHAR(255) NULL,
    reject_reason VARCHAR(255) NULL,
    record_time DATETIME NOT NULL,
    client_send_time DATETIME NULL,
    server_receive_time DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_driver_track_sequence (trip_id, driver_id, sequence_no, deleted),
    KEY idx_driver_track_trip_time (trip_id, record_time),
    KEY idx_driver_track_driver_time (driver_id, record_time),
    KEY idx_driver_track_status (trip_id, point_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS driver_track_distance_record (
    id BIGINT PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    total_distance INT NOT NULL DEFAULT 0,
    last_settle_distance INT NOT NULL DEFAULT 0,
    settle_type VARCHAR(32) NOT NULL,
    settle_key VARCHAR(128) NOT NULL,
    settle_time DATETIME NOT NULL,
    event_published TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_driver_track_distance_settle_key (settle_key, deleted),
    KEY idx_driver_track_distance_trip_driver (trip_id, driver_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS driver_track_deviation_record (
    id BIGINT PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    longitude DECIMAL(10,6) NOT NULL,
    latitude DECIMAL(10,6) NOT NULL,
    deviation_distance INT NOT NULL DEFAULT 0,
    deviation_status TINYINT NOT NULL DEFAULT 0,
    record_time DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    KEY idx_driver_track_deviation_trip_driver_time (trip_id, driver_id, record_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS trip_track_summary (
    id BIGINT PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    primary_user_id BIGINT NOT NULL,
    raw_distance_meters INT NOT NULL DEFAULT 0,
    filtered_distance_meters INT NOT NULL DEFAULT 0,
    approved_distance_meters INT NOT NULL DEFAULT 0,
    total_point_count INT NOT NULL DEFAULT 0,
    valid_point_count INT NOT NULL DEFAULT 0,
    invalid_point_count INT NOT NULL DEFAULT 0,
    location_gap_count INT NOT NULL DEFAULT 0,
    warning_count INT NOT NULL DEFAULT 0,
    hard_anomaly_count INT NOT NULL DEFAULT 0,
    risk_score INT NOT NULL DEFAULT 0,
    risk_level VARCHAR(16) NOT NULL DEFAULT 'LOW',
    settlement_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    review_reason VARCHAR(255) NULL,
    reviewer_id BIGINT NULL,
    reviewed_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_trip_track_summary_trip (trip_id, deleted),
    KEY idx_trip_track_summary_risk (risk_level, settlement_status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS trip_track_anomaly (
    id BIGINT PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    previous_point_id BIGINT NULL,
    current_point_id BIGINT NULL,
    anomaly_type VARCHAR(64) NOT NULL,
    risk_score INT NOT NULL DEFAULT 0,
    detail_json JSON NULL,
    occurred_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    KEY idx_trip_track_anomaly_trip_time (trip_id, occurred_at),
    KEY idx_trip_track_anomaly_user_time (user_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
