create table if not exists payment_record (
    id bigint not null comment '记录主键',
    order_id bigint not null comment '订单ID',
    order_no varchar(64) not null default '' comment '订单编号',
    payment_no varchar(64) not null comment '支付编号',
    wx_prepay_id varchar(128) null comment '微信预支付ID',
    wx_transaction_id varchar(128) null comment '微信交易ID',
    pay_channel varchar(32) not null comment 'PAY通知或投递渠道',
    pay_amount decimal(12,2) not null default 0.00 comment '支付金额',
    payment_status varchar(32) not null comment '支付状态',
    callback_payload text null comment '第三方回调原始载荷',
    paid_at datetime null comment '支付时间',
    created_at datetime not null comment '记录创建时间',
    updated_at datetime not null comment '记录最后更新时间',
    deleted tinyint not null default 0 comment '逻辑删除标记：0未删除、1已删除',
    primary key (id),
    unique key uk_payment_no (payment_no),
    unique key uk_payment_wx_transaction (wx_transaction_id),
    key idx_payment_order (order_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='支付记录表';

create table if not exists payment_refund_record (
    id bigint not null comment '记录主键',
    order_id bigint not null comment '订单ID',
    refund_no varchar(64) not null comment '退款编号',
    wx_refund_id varchar(128) null comment '微信退款ID',
    user_id bigint not null comment '平台用户ID',
    refund_amount decimal(12,2) not null default 0.00 comment '退款金额',
    refund_reason varchar(255) not null default '' comment '退款原因',
    refund_type varchar(32) not null comment '退款类型',
    refund_status varchar(32) not null comment '退款状态',
    audit_status varchar(32) not null comment '审核状态',
    callback_payload text null comment '第三方回调原始载荷',
    requested_at datetime not null comment '申请时间',
    refunded_at datetime null comment '退款时间',
    created_at datetime not null comment '记录创建时间',
    updated_at datetime not null comment '记录最后更新时间',
    deleted tinyint not null default 0 comment '逻辑删除标记：0未删除、1已删除',
    primary key (id),
    unique key uk_payment_refund_no (refund_no),
    key idx_payment_refund_order (order_id),
    key idx_payment_refund_status (refund_status, audit_status)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='支付退款记录表';

create table if not exists payment_profit_sharing_record (
    id bigint not null comment '记录主键',
    order_id bigint not null comment '订单ID',
    merchant_id bigint not null comment '商家ID',
    verification_id bigint not null comment '核销ID',
    sharing_no varchar(64) not null comment '分账编号',
    wx_sharing_id varchar(128) null comment '微信分账ID',
    total_amount decimal(12,2) not null default 0.00 comment '总计金额',
    platform_commission_amount decimal(12,2) not null default 0.00 comment '平台佣金金额',
    merchant_amount decimal(12,2) not null default 0.00 comment '商家金额',
    commission_rate decimal(5,4) not null default 0.0000 comment '佣金比例',
    sharing_status varchar(32) not null comment '分账状态',
    callback_payload text null comment '第三方回调原始载荷',
    shared_at datetime null comment '分账完成时间',
    created_at datetime not null comment '记录创建时间',
    updated_at datetime not null comment '记录最后更新时间',
    deleted tinyint not null default 0 comment '逻辑删除标记：0未删除、1已删除',
    primary key (id),
    unique key uk_payment_sharing_no (sharing_no),
    key idx_payment_sharing_order (order_id),
    key idx_payment_sharing_merchant (merchant_id, created_at),
    key idx_payment_sharing_status (sharing_status)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='支付分账分账记录表';
