package com.tongluxing.trip.vo;

import java.math.BigDecimal;
import java.util.List;

/** 行程详情响应。P0 新增字段均放在尾部，旧客户端可安全忽略。 */
public record TripResponse(
        String tripId,
        String tripNumber,
        String userId,
        String vehicleId,
        String title,
        String description,
        Integer expectedPeople,
        String startName,
        BigDecimal startLat,
        BigDecimal startLng,
        LocationResponse startLocation,
        String endName,
        BigDecimal endLat,
        BigDecimal endLng,
        LocationResponse endLocation,
        String routeSummary,
        String routePolylineKey,
        Integer routeDistance,
        Integer routeDuration,
        String routePolyline,
        String departureTime,
        Integer estimatedDays,
        Integer totalDistanceMeters,
        Integer maxVehicleCount,
        Integer joinedVehicleCount,
        List<String> vehicleRequirements,
        String budgetDescription,
        String travelDepth,
        Boolean publicFlag,
        String status,
        String remark,
        String actualStartTime,
        String actualEndTime,
        List<WaypointLocationResponse> waypoints,
        String createdAt,
        String updatedAt,
        String tripType,
        String publisherRole,
        String captainUserId,
        Boolean autoStartEnabled,
        String arrivalStatus,
        String arrivalEnteredAt,
        String arrivalDecisionDeadline,
        Integer continueCount,
        Boolean passengerDemand,
        Boolean hasCaptain
) {
}
