server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  application:
    name: tongdao-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:db/auth-schema.sql
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
      timeout: ${REDIS_TIMEOUT}
  security:
    user:
      name: ${SECURITY_DEV_USERNAME}
      password: ${SECURITY_DEV_PASSWORD}
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  web:
    resources:
      add-mappings: false

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.tongdao.*.entity
  configuration:
    map-underscore-to-camel-case: true

wx:
  miniapp:
    app-id: ${WX_MINIAPP_APP_ID}
    app-secret: ${WX_MINIAPP_APP_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.tongdao: debug
