CREATE TABLE IF NOT EXISTS team (
  id BIGINT NOT NULL comment '记录主键',
  trip_id BIGINT NOT NULL comment '行程ID',
  owner_user_id BIGINT NOT NULL comment '队长用户ID',
  owner_vehicle_id BIGINT NOT NULL comment '队长车辆ID',
  team_name VARCHAR(64) NOT NULL comment '队伍名称',
  team_desc VARCHAR(255) NULL comment '队伍说明',
  start_name VARCHAR(128) NOT NULL comment '起点名称',
  end_name VARCHAR(128) NOT NULL comment '终点名称',
  departure_time DATETIME NOT NULL comment '出发时间',
  max_member_count INT NOT NULL comment '最高成员数量',
  current_member_count INT NOT NULL DEFAULT 1 comment '当前成员数量',
  join_mode VARCHAR(20) NOT NULL DEFAULT 'APPROVAL' comment '加入模式',
  team_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' comment '队伍状态',
  public_flag TINYINT(1) NOT NULL DEFAULT 1 comment '是否公开：0否、1是',
  chat_conversation_id BIGINT NULL comment '聊天会话ID',
  notice VARCHAR(255) NULL comment '公告',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP comment '记录创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '记录最后更新时间',
  deleted TINYINT(1) NOT NULL DEFAULT 0 comment '逻辑删除标记：0未删除、1已删除',
  PRIMARY KEY (id),
  KEY idx_team_trip (trip_id, team_status),
  KEY idx_team_owner (owner_user_id, team_status),
  KEY idx_team_public_time (public_flag, team_status, departure_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='队伍表';

CREATE TABLE IF NOT EXISTS team_member (
  id BIGINT NOT NULL comment '记录主键',
  team_id BIGINT NOT NULL comment '队伍ID',
  user_id BIGINT NOT NULL comment '平台用户ID',
  vehicle_id BIGINT NULL comment '车辆ID',
  member_role VARCHAR(20) NOT NULL DEFAULT 'MEMBER' comment '成员角色',
  member_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' comment '成员状态',
  joined_at DATETIME NOT NULL comment '加入时间',
  exited_at DATETIME NULL comment '退出时间',
  nickname_snapshot VARCHAR(64) NULL comment '昵称快照',
  vehicle_snapshot VARCHAR(128) NULL comment '车辆快照',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP comment '记录创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '记录最后更新时间',
  deleted TINYINT(1) NOT NULL DEFAULT 0 comment '逻辑删除标记：0未删除、1已删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_team_member_user (team_id, user_id, deleted),
  KEY idx_team_member_team (team_id, member_status),
  KEY idx_team_member_user_status (user_id, member_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='队伍成员表';

CREATE TABLE IF NOT EXISTS team_join_application (
  id BIGINT NOT NULL comment '记录主键',
  team_id BIGINT NOT NULL comment '队伍ID',
  trip_id BIGINT NULL comment '行程ID',
  applicant_user_id BIGINT NOT NULL comment '申请人用户ID',
  applicant_vehicle_id BIGINT NULL comment '申请人车辆ID',
  reviewer_user_id BIGINT NULL comment '审核人用户ID',
  application_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' comment '申请状态',
  apply_message VARCHAR(255) NULL comment '申请说明',
  join_question_json JSON NULL comment '加入问题JSON数据',
  review_message VARCHAR(255) NULL comment '审核说明',
  reviewed_at DATETIME NULL comment '审核时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP comment '记录创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '记录最后更新时间',
  deleted TINYINT(1) NOT NULL DEFAULT 0 comment '逻辑删除标记：0未删除、1已删除',
  PRIMARY KEY (id),
  KEY idx_team_apply_applicant (applicant_user_id, application_status, created_at),
  KEY idx_team_apply_team (team_id, application_status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='队伍加入申请表';

CREATE TABLE IF NOT EXISTS team_audit_log (
  id BIGINT NOT NULL comment '记录主键',
  team_id BIGINT NOT NULL comment '队伍ID',
  operator_user_id BIGINT NOT NULL comment '管理员用户ID',
  operation_type VARCHAR(32) NOT NULL comment '操作类型',
  before_json JSON NULL comment '操作前数据快照JSON',
  after_json JSON NULL comment '操作后数据快照JSON',
  remark VARCHAR(255) NULL comment '业务备注',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP comment '记录创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '记录最后更新时间',
  deleted TINYINT(1) NOT NULL DEFAULT 0 comment '逻辑删除标记：0未删除、1已删除',
  PRIMARY KEY (id),
  KEY idx_team_audit_team_time (team_id, created_at),
  KEY idx_team_audit_operator_time (operator_user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='队伍审核日志表';
