package com.tongdao.invite.service.impl;
import java.time.LocalDateTime;import java.util.*;import org.springframework.beans.factory.ObjectProvider;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.tongdao.common.exception.BusinessException;import com.tongdao.common.result.ResultCode;import com.tongdao.common.utils.SnowflakeIdGenerator;import com.tongdao.invite.integration.*;import com.tongdao.invite.integration.InviteFacade.InviteRewardResult;import com.tongdao.invite.mapper.InviteMapper;import com.tongdao.invite.service.InviteService;import com.tongdao.user.model.UserModels.*;import com.tongdao.user.support.CurrentUserContext;import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor public class InviteServiceImpl implements InviteService {
 private final InviteMapper mapper; private final CurrentUserContext currentUser; private final ObjectProvider<InviteRewardPort> rewardPort;
 @Override public InviteCodeVO currentCode(){return getCode(currentUser.requireUserId());}
 @Override public InviteBindVO bindCurrent(String code){return bind(currentUser.requireUserId(),code);}
 @Override public InviteRewardProgressVO currentProgress(){return getProgress(currentUser.requireUserId());}
 @Override public PageResult<InvitationVO> currentRecords(String status,int page,int size){return getRecords(currentUser.requireUserId(),status,page,size);}
 @Override public InviteCodeVO getCode(Long userId){Map<String,Object> row=mapper.findCodeByUser(userId);if(row==null){for(int i=0;i<5&&row==null;i++){try{mapper.insertCode(SnowflakeIdGenerator.nextId(),userId,code(userId,i),LocalDateTime.now());}catch(DuplicateKeyException ignored){}row=mapper.findCodeByUser(userId);}}return new InviteCodeVO(str(row,"inviteCode"),"inviteCode="+str(row,"inviteCode"),bool(row,"enabledFlag"));}
 @Override @Transactional public InviteBindVO bind(Long invitee,String code){if(invitee==null||code==null||code.isBlank())throw new BusinessException(ResultCode.BAD_REQUEST,"邀请码不能为空");Map<String,Object> owner=mapper.findCode(code.trim());if(owner==null)throw new BusinessException(ResultCode.NOT_FOUND,"邀请码不存在");long inviter=lng(owner,"userId");if(inviter==invitee)throw new BusinessException(409,"不能绑定自己的邀请码");if(mapper.findRelationIdByInvitee(invitee)!=null)throw new BusinessException(409,"邀请关系已绑定");if(mapper.createsCycle(inviter,invitee)>0)throw new BusinessException(409,"邀请关系形成循环");LocalDateTime now=LocalDateTime.now();try{mapper.insertRelation(SnowflakeIdGenerator.nextId(),inviter,invitee,code.trim(),now);}catch(DuplicateKeyException e){throw new BusinessException(409,"邀请关系已绑定");}return new InviteBindVO(inviter,invitee,"BOUND",now);}
 @Override public InviteRewardProgressVO getProgress(Long userId){int count=mapper.countValid(userId);return new InviteRewardProgressVO(count,next(count),mapper.findGrantedRules(userId));}
 @Override public PageResult<InvitationVO> getRecords(Long userId,String status,int page,int size){int p=Math.max(1,page),s=Math.min(100,Math.max(1,size));List<InvitationVO> rows=mapper.findRecords(userId,status,(p-1)*s,s).stream().map(this::record).toList();return new PageResult<>(rows,mapper.countRecords(userId,status),p,s);}
 @Override @Transactional public InviteRewardResult completeFirstTeam(Long userId,Long teamId,String bizId){Map<String,Object> relation=mapper.findRelationForUpdate(userId);if(relation==null)return new InviteRewardResult(null,null,bizId,"NO_RELATION");long relationId=lng(relation,"relationId"),inviter=lng(relation,"inviterUserId");LocalDateTime now=LocalDateTime.now();mapper.markValid(relationId,now);String rewardBizNo="INVITE_FIRST_TEAM:"+relationId+":"+bizId;try{mapper.insertReward(SnowflakeIdGenerator.nextId(),relationId,inviter,"FIRST_TEAM",rewardBizNo,"{\"growthPoints\":100}",now);}catch(DuplicateKeyException e){return new InviteRewardResult(relationId,inviter,rewardBizNo,"DUPLICATE");}try{InviteRewardPort port=rewardPort.getIfAvailable();if(port==null)throw new IllegalStateException("reward port unavailable");port.grantInviteReward(inviter,rewardBizNo,"FIRST_TEAM");mapper.updateReward(rewardBizNo,"GRANTED",null,now,now);return new InviteRewardResult(relationId,inviter,rewardBizNo,"GRANTED");}catch(RuntimeException e){mapper.updateReward(rewardBizNo,"FAILED",e.getMessage(),null,now);return new InviteRewardResult(relationId,inviter,rewardBizNo,"FAILED");}}
 private InvitationVO record(Map<String,Object> r){return new InvitationVO(lng(r,"relationId"),lng(r,"inviteeUserId"),str(r,"inviteCode"),str(r,"status"),time(r,"boundAt"),time(r,"firstTeamCompletedAt"));} private String code(long id,int salt){return Long.toUnsignedString(id+salt*97L,36).toUpperCase(Locale.ROOT).substring(0,Math.min(10,Long.toUnsignedString(id+salt*97L,36).length()));} private int next(int c){for(int n:new int[]{1,3,5,10})if(c<n)return n-c;return 0;} private String str(Map<String,Object>r,String k){Object v=r.get(k);return v==null?"":v.toString();}private long lng(Map<String,Object>r,String k){Object v=r.get(k);return v instanceof Number n?n.longValue():Long.parseLong(v.toString());}private boolean bool(Map<String,Object>r,String k){Object v=r.get(k);return v instanceof Number n?n.intValue()!=0:Boolean.parseBoolean(String.valueOf(v));}private LocalDateTime time(Map<String,Object>r,String k){Object v=r.get(k);return v==null?null:v instanceof LocalDateTime t?t:LocalDateTime.parse(v.toString().replace(' ','T'));}
}
