CREATE TABLE IF NOT EXISTS file_storage (
  id BIGINT NOT NULL comment '记录主键',
  bucket VARCHAR(128) NOT NULL comment '存储桶',
  object_key VARCHAR(512) NOT NULL comment '对象标识或存储Key',
  original_file_name VARCHAR(255) NOT NULL comment '原始文件名称',
  content_type VARCHAR(128) NOT NULL comment '内容类型',
  file_size BIGINT NOT NULL comment '文件大小，单位为字节',
  biz_type VARCHAR(64) NOT NULL comment '关联业务类型',
  biz_id VARCHAR(128) NULL comment '关联业务单据标识',
  user_id BIGINT NULL comment '平台用户ID',
  storage_type VARCHAR(32) NOT NULL DEFAULT 'MINIO' comment '存储类型',
  upload_status VARCHAR(32) NOT NULL DEFAULT 'CONFIRMED' comment '上传状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP comment '记录创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '记录最后更新时间',
  deleted TINYINT NOT NULL DEFAULT 0 comment '逻辑删除标记：0未删除、1已删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_file_object (bucket, object_key, deleted),
  KEY idx_file_biz (biz_type, biz_id, deleted),
  KEY idx_file_user (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='文件存储表';
