import { apiRequest } from './apiClient.js'
export const getOverview = () => apiRequest('/v1/merchants/center/overview')
export const getStores = () => apiRequest('/v1/merchants/stores')
export const createStore = data => apiRequest('/v1/merchants/stores', { method: 'POST', body: JSON.stringify(data) })
export const getCoupons = () => apiRequest('/v1/merchants/coupon-offers')
export const createCoupon = data => apiRequest('/v1/merchants/coupon-offers', { method: 'POST', body: JSON.stringify(data) })
export const resubmitCoupon = (id, data) => apiRequest(`/v1/merchants/coupon-offers/${id}/resubmit`, { method: 'PUT', body: JSON.stringify(data) })
export const getApplication = () => apiRequest('/v1/merchants/applications/me/latest')
export const saveSettlement = data => apiRequest('/v1/merchants/me/settlement-account', { method: 'PUT', body: JSON.stringify(data) })
export const getSettlements = (status = '') => apiRequest(`/v1/merchants/settlements?status=${encodeURIComponent(status)}&page=1&size=50`)
export const getGroupbuyActivities = (status = '') => apiRequest(`/v1/groupbuys/merchant/me?status=${encodeURIComponent(status)}&page=1&size=50`)
export const getProducts = (status = '') => apiRequest(`/v1/merchants/products?status=${encodeURIComponent(status)}&page=1&size=100`)
export const createProduct = data => apiRequest('/v1/merchants/products', { method: 'POST', body: JSON.stringify(data) })
export const offShelfProduct = id => apiRequest(`/v1/merchants/products/${id}/off-shelf`, { method: 'PUT' })
export const getOrders = (status = '') => apiRequest(`/v1/merchants/orders?status=${encodeURIComponent(status)}&page=1&size=100`)
export const getVerifications = () => apiRequest('/v1/verifications?page=1&size=100')
export const parseVerification = code => apiRequest('/v1/verifications/parse', { method: 'POST', body: JSON.stringify({ code }) })
export const confirmVerification = data => apiRequest('/v1/verifications/confirm', { method: 'POST', body: JSON.stringify(data) })
export const getPartnerApplication = () => apiRequest('/v1/merchants/partner-application')
export const applyPartner = data => apiRequest('/v1/merchants/partner-application', { method: 'POST', body: JSON.stringify(data) })
export const cancelPartner = reason => apiRequest('/v1/merchants/partner-application/cancellation', { method: 'POST', body: JSON.stringify({ reason }) })
export const getPartnerCoupons = () => apiRequest('/v1/merchants/coupons')
export const createPartnerCoupon = data => apiRequest('/v1/merchants/coupons', { method: 'POST', headers: { 'X-Request-Id': `PARTNER-COUPON-${Date.now()}` }, body: JSON.stringify(data) })
