CREATE TABLE IF NOT EXISTS coupon_template (
  id BIGINT NOT NULL comment '记录主键',
  coupon_name VARCHAR(64) NOT NULL comment '优惠券名称',
  coupon_type VARCHAR(24) NOT NULL comment '优惠券类型',
  issuer_id BIGINT NULL comment '发行方ID',
  threshold_amount DECIMAL(10,2) NOT NULL DEFAULT 0 comment '门槛金额',
  discount_amount DECIMAL(10,2) NOT NULL comment '优惠金额',
  scope_json JSON NOT NULL comment '适用范围JSON数据',
  validity_type VARCHAR(16) NOT NULL comment '有效期类型',
  valid_days INT NULL comment '有效，单位为天',
  valid_start_at DATETIME NULL comment '有效起点时间',
  valid_end_at DATETIME NULL comment '有效终点时间',
  total_quantity INT NOT NULL comment '总计数量',
  claimed_quantity INT NOT NULL DEFAULT 0 comment '已领取数量',
  per_user_limit INT NOT NULL DEFAULT 1 comment '每名用户可领取数量上限',
  template_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' comment '模板状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP comment '记录创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '记录最后更新时间',
  deleted TINYINT NOT NULL DEFAULT 0 comment '逻辑删除标记：0未删除、1已删除',
  PRIMARY KEY (id),
  KEY idx_coupon_template_status (template_status, valid_start_at, valid_end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='优惠券模板表';
CREATE TABLE IF NOT EXISTS coupon_user (
  id BIGINT NOT NULL comment '记录主键',
  user_id BIGINT NOT NULL comment '平台用户ID',
  template_id BIGINT NOT NULL comment '模板ID',
  source_type VARCHAR(24) NOT NULL comment '来源类型',
  source_biz_id VARCHAR(64) NOT NULL comment '来源业务ID',
  coupon_status VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE' comment '优惠券状态',
  valid_start_at DATETIME NOT NULL comment '有效起点时间',
  valid_end_at DATETIME NOT NULL comment '有效终点时间',
  locked_order_id BIGINT NULL comment '锁定订单ID',
  used_order_id BIGINT NULL comment '使用订单ID',
  used_at DATETIME NULL comment '使用时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP comment '记录创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '记录最后更新时间',
  deleted TINYINT NOT NULL DEFAULT 0 comment '逻辑删除标记：0未删除、1已删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_coupon_user_source (user_id, template_id, source_type, source_biz_id, deleted),
  KEY idx_coupon_user_status (user_id, coupon_status, valid_end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment='优惠券用户表';
